# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-15 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
