# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-17 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
