# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-31 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModelForHad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=32)),
                ('file_path', models.CharField(max_length=64)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('task_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FileModelForUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=64)),
            ],
        )
    ]
