# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-08 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
    ]
