# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0002_auto_20190108_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesosCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clusterName', models.CharField(max_length=32)),
                ('masterNodeNum', models.IntegerField()),
                ('masterPort', models.IntegerField()),
                ('masterImage', models.CharField(max_length=128)),
                ('zkImage', models.CharField(max_length=128)),
                ('masterDeploy', models.CharField(max_length=256)),
                ('marathonID', models.CharField(max_length=32)),
                ('marathonPort', models.IntegerField()),
                ('marathonZK', models.CharField(max_length=128)),
                ('marathonImage', models.CharField(max_length=128)),
                ('marathonDeploy', models.CharField(max_length=256)),
                ('haproxyID', models.CharField(max_length=32)),
                ('servicePort', models.IntegerField()),
                ('statusPort', models.IntegerField()),
                ('bambooPort', models.IntegerField()),
                ('haproxyMarathon', models.CharField(max_length=128)),
                ('haproxImage', models.CharField(max_length=128)),
                ('haproxyDeploy', models.CharField(max_length=256)),
                ('slaveLabel', models.CharField(max_length=32)),
                ('slavePort', models.IntegerField()),
                ('slaveZK', models.CharField(max_length=128)),
                ('slaveImage', models.CharField(max_length=128)),
                ('slaveDeploy', models.CharField(max_length=256)),
            ],
        ),
    ]
