# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-03 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_sysuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysrole',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='\u89d2\u8272\u540d'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.SysRole'),
        ),
    ]
