# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-01 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20181231_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('file_from', models.IntegerField(choices=[(1, '\u672c\u5730\u4e0a\u4f20'), (2, '\u5df2\u6709\u6587\u4ef6'), (3, '\u6587\u4ef6\u5730\u5740')], default=1)),
                ('send_model', models.IntegerField(choices=[(1, 'ansible'), (2, 'murder p2p')], default=1)),
                ('total_file', models.IntegerField()),
                ('total_host', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, '\u5b8c\u6210'), (2, '\u672a\u5b8c\u6210'), (3, '\u5f02\u5e38')], default=2)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.IntegerField(blank=True, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='filelog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.SysUser'),
        )
    
    ]
