# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-27 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20181223_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=8, verbose_name='\u4efb\u52a1ID')),
                ('step', models.CharField(max_length=32)),
                ('task', models.CharField(max_length=32)),
                ('host', models.GenericIPAddressField(verbose_name='\u4e3b\u673aIP')),
                ('status', models.BooleanField()),
                ('msg', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnsibleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(1, '\u5b8c\u6210'), (2, '\u672a\u5b8c\u6210'), (3, '\u5f02\u5e38')], default=2)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.IntegerField(blank=True, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
