# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-04 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181104_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='template_name',
            field=models.CharField(default='home/dashboard.html', max_length=64),
            preserve_default=False,
        ),
    ]
