# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-06 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_homepage_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethost',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.HostGroup', verbose_name='\u4e3b\u673a\u7ec4'),
            preserve_default=False,
        ),
    ]
