# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-06 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20181106_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostmodifylog',
            name='assert_no',
        ),
        migrations.RemoveField(
            model_name='hostgroup',
            name='host_number',
        ),
        migrations.DeleteModel(
            name='HostModifyLog',
        ),
    ]
