# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-06 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20181106_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgroup',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='\u7535\u8bdd'),
        ),
    ]
