# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-06 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20181106_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostgroup',
            old_name='groupname',
            new_name='name',
        ),
    ]
