# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-16 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20181106_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=16, verbose_name='\u6587\u4ef6\u540d')),
                ('total_line', models.IntegerField(default=0, verbose_name='\u884c\u6570')),
                ('succeeded_line', models.IntegerField(default=0, verbose_name='\u5904\u7406\u6210\u529f')),
                ('failure_line', models.IntegerField(default=0, verbose_name='\u5904\u7406\u5931\u8d25')),
            ],
        ),
        migrations.AlterField(
            model_name='assethost',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.HostGroup', verbose_name='\u4e3b\u673a\u7ec4'),
        ),
    ]
