# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20181116_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostimport',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
