# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-16 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_hostimport_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostimport',
            name='err_line',
            field=models.CharField(default=None, max_length=64, verbose_name='\u9519\u8bef\u884c\u53f7'),
        ),
    ]
