# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_hostimport_err_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostimport',
            name='err_line',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u9519\u8bef\u884c\u53f7'),
        ),
    ]
