# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-21 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_hostimport_err_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethost',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU\u578b\u53f7'),
        ),
    ]
