# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-21 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20181121_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, '\u4ee3\u7406\u5b89\u88c5'), (2, '\u4fe1\u606f\u6536\u96c6')])),
                ('is_succeeded', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.AssetHost')),
            ],
        ),
    ]
