# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_hostevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostevent',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
