# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-22 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20181121_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostevent',
            name='action',
            field=models.IntegerField(choices=[(1, '\u4ee3\u7406\u5b89\u88c5'), (2, '\u89c4\u683c\u4fe1\u606f\u6536\u96c6'), (3, '\u89c4\u683c\u4fe1\u606f\u5237\u65b0')]),
        ),
    ]
