# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20181122_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethost',
            name='ower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.SysUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cmdtemplate',
            name='name',
            field=models.CharField(max_length=32, verbose_name='\u5267\u672c\u540d'),
        ),
    ]
