# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-29 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20181123_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('script_type', models.IntegerField(choices=[(1, 'bash'), (2, 'python'), (3, 'perl')])),
                ('script_from', models.CharField(max_length=16)),
                ('script_file', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('script_ower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.SysUser')),
            ],
        ),
    ]
