# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_scriptmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptmodel',
            name='script_from',
            field=models.IntegerField(choices=[(1, 'manully'), (2, '\u672c\u5730\u5bfc\u5165'), (3, '\u5df2\u6709\u811a\u672c')]),
        ),
    ]
