# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-02 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_hostuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostuser',
            name='msg',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
