# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20181202_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptmodel',
            name='total_run_count',
            field=models.IntegerField(default=0),
        ),
    ]
