# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_scriptmodel_total_run_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.GenericIPAddressField(verbose_name='\u4e3b\u673aIP')),
                ('host_account', models.CharField(max_length=10, verbose_name='\u5e10\u53f7')),
            ],
        ),
        migrations.RemoveField(
            model_name='cronlist',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='taskdetail',
            name='task_id',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='execute_ower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.SysUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklog',
            name='script_file',
            field=models.CharField(default='5f94fbc7.sh', max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CronList',
        ),
        migrations.DeleteModel(
            name='TaskDetail',
        ),
        migrations.AddField(
            model_name='taskhost',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TaskLog', verbose_name='\u4efb\u52a1ID'),
        ),
    ]
