# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-05 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20181205_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='task_id',
            field=models.CharField(max_length=8, verbose_name='\u4efb\u52a1ID'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task_type',
            field=models.IntegerField(choices=[(1, '\u811a\u672c\u6267\u884c'), (2, 'Ansible'), (3, '\u5feb\u901f\u5de5\u5177')], verbose_name='\u7c7b\u578b'),
        ),
    ]
