# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-06 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20181205_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='execute_ower',
            new_name='execute_owner',
        ),
        migrations.AddField(
            model_name='taskhost',
            name='execute_status',
            field=models.IntegerField(choices=[(1, '\u6210\u529f'), (2, '\u5931\u8d25')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskhost',
            name='task_id',
            field=models.CharField(max_length=8, verbose_name='\u4efb\u52a1ID'),
        ),
    ]
