# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_auto_20181206_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('script_from', models.IntegerField(choices=[(1, '\u624b\u52a8\u5f55\u5165'), (2, '\u672c\u5730\u5bfc\u5165'), (3, '\u5df2\u6709\u811a\u672c')])),
                ('script_file', models.CharField(max_length=64)),
                ('total_run_count', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('script_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.SysUser')),
            ],
        ),
        migrations.RenameField(
            model_name='assethost',
            old_name='ower',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='scriptmodel',
            old_name='script_ower',
            new_name='script_owner',
        ),
        migrations.AlterField(
            model_name='scriptmodel',
            name='script_from',
            field=models.IntegerField(choices=[(1, '\u624b\u52a8\u5f55\u5165'), (2, '\u672c\u5730\u5bfc\u5165'), (3, '\u5df2\u6709\u811a\u672c')], default=1),
        ),
        migrations.AlterField(
            model_name='scriptmodel',
            name='script_type',
            field=models.IntegerField(choices=[(1, 'bash'), (2, 'python'), (3, 'perl')], default=1),
        ),
        migrations.AlterField(
            model_name='scriptmodel',
            name='total_run_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
