# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-13 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_auto_20181207_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ansiblemodel',
            old_name='script_owner',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='ansiblemodel',
            name='script_file',
        ),
        migrations.RemoveField(
            model_name='ansiblemodel',
            name='script_from',
        ),
        migrations.AddField(
            model_name='ansiblemodel',
            name='dir_name',
            field=models.CharField(default='lamp', max_length=32, verbose_name='\u4fdd\u5b58\u76ee\u5f55'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ansiblemodel',
            name='total_role_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ansiblemodel',
            name='total_task_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
